name: Comment TeaKit results

on:
  workflow_call:

permissions:
  actions: read
  pull-requests: write

jobs:
  comment:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: iamkaf/multiloader-conventions/.github/actions/comment-teakit@950effa52ff135305b1feb0a73fe7b50296de5f3
