name: Comment TeaKit results

on:
  workflow_call:

permissions:
  actions: read
  pull-requests: write

jobs:
  comment:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: iamkaf/multiloader-conventions/.github/actions/comment-teakit@eac6c241b2ebe1a437b43f7ecd7a8cde760d9262
