name: Comment TeaKit results

on:
  workflow_call:

permissions:
  actions: read
  pull-requests: write

jobs:
  comment:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: iamkaf/multiloader-conventions/.github/actions/comment-teakit@8a67e324e295ed3c768cada1d2055cebbf1c8111
